# Generated by Django 6.0.1 on 2026-01-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0003_alter_patientprofile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SymptomAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptoms_text", models.TextField()),
                ("predicted_specialty", models.CharField(max_length=100)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("ai_model_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptom_analyses",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
    ]
